import { TCategory } from './category';
import { TInventoryItem } from './product';

export type TCartProduct = {
  _id?: string;
  sku?: string;
  singleQuantityPrice?: number;
  totalPrice?: number;
  quantity?: number;
  title?: string;
  image?: string;
  slug?: string;
  forging_style?: string;
  model_group?: string;
  maxInventory?: number;
  minInventory?: number;
  inventoryStep?: number;
  vehicleInformation?: string;
  cartPackage?: string;
  cartSerial?: string;
  category?: TCategory;
  isFrontTire?: boolean;
  isRearTire?: boolean;
  item_image?: string;
  sidewall?: string;
  load_rating?: string;
  tire_load_index?: string;
  speed_rating?: string;
  item_class?: string;
  inventory_available?: number;
  tirePackageUrl?: string;
  metaData?: {
    frontForging?: string;
    rearForging?: string;
    frontDiameter?: string;
    rearDiameter?: string;
    frontWidth?: string;
    rearWidth?: string;
    frontLipSize?: string;
    rearLipSize?: string;
    finishType?: string;
    standardFinish?: string;
    horn?: string;
    customFinish?: string;
    centerCapTitle?: string;
    wantWidestPossibleWidth?: boolean;
    multiPiece?: string;
    letAmaniForgedDetermineSize?: boolean;
    lugBoltFinish?: string;
    selectedHorn?: string;
    year?: string;
    make?: string;
    model?: string;
    bodyType?: string;
    subModel?: string;
    coupon?: string;
    totalProvidedDiscount?: number;
  };
} & Partial<TInventoryItem>;
