import { TCategory } from './category';

export type TInventoryItem = {
  internal_id?: string;
  slug: string;
  name?: string;
  title?: string;
  item_type?: string;
  item_class?: string;
  brand?: string;
  model_group?: string;
  category?: TCategory;
  forging_style?: string;
  wheel_size?: string;
  wheel_diameter?: string;
  wheel_width?: string;
  finish?: string;
  lip_size?: string;
  offset?: string;
  bolt_pattern_1?: string;
  bolt_pattern_2?: string;
  centerbore?: string;
  load_rating?: string;
  xfactor?: string;
  yfactor?: string;
  backspacing?: string;
  raw_size?: string;
  tire_width?: string;
  tire_aspect_ratio?: string;
  tire_diameter?: string;
  ship_weight?: string;
  ship_width?: string;
  ship_height?: string;
  ship_depth?: string;
  purchase_description?: string;
  short_description?: string;
  item_image?: string;
  msrp?: number;
  price?: number;
  inventory_available?: number;
  build_available?: string;
  steering_wheel_addon_options_1?: string;
  steering_wheel_addon_options_2?: string;
  steering_wheel_addon_options_3?: string;
  terrain?: {
    text: string;
    value: string;
  };
  blank_bolt_patterns?: string;
  design_type?: string;
  style?: string;
  dually?: boolean;
  finish_type?: string;
  suspension_type?: string;
  tire_type?: {
    text: string;
    value: string;
  }[];
  speed_rating?: string;
  sidewall?: {
    text: string;
    value: string;
  };
  tire_load_index?: string;
  tire_max_load_lbs?: string;
  tire_max_load_lbs_2?: string;
  tire_max_load_kg?: string;
  tire_max_load_kg_2?: string;
  ply?: string;
  approved_rim_contours?: string;
  tread_depth_32nds?: string;
  tread_depth_mm?: string;
  std_rim?: string;
  max_air_pressure_kpa?: string;
  max_air_pressure_psi?: string;
  tire_size?: string;
  seo_description?: string;
  front_size?: string;
  rear_size?: string;
  front_diameter?: string;
  front_width?: string;
  rear_diameter?: string;
  rear_width?: string;
  dealer_price?: string;
};

export type TInventoryListItem = {
  _id?: string;
  title?: string;
  slug?: string;
  brand?: string;
  sku?: string;
  model_group?: string;
  tire_type?: string[];
  renderedImages?: { series: string; path: string }[];
  createdAt?: string;
  updatedAt?: string;
  item_image?: string;
  inventory_available?: number;
  msrp?: number;
  price?: number;
  category?: TCategory;
  wheel_size?: string;
  finish?: string;
  lip_size?: string;
  bolt_pattern_1?: string;
  purchase_description?: string;
  min_price?: number;
};
